name: reviza
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
      
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_pdfview: ^1.3.2
  flutter_gemini: ^2.0.0
  lottie: ^2.7.0
  flutter_markdown: ^0.6.18+2
  image_picker: ^1.0.5
  flutter_highlighter: ^0.1.1
  flutter_math_fork: ^0.7.2
  equatable: ^2.0.5
  authentication_repository:
    path: packages/auth_packages/authentication_repository
  bloc: ^8.1.0
  flow_builder: ^0.0.9
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/auth_packages/form_inputs
  formz: ^0.6.0
  google_fonts: ^6.2.1
  study_material_api:
    path: packages/crud_packages/study_material_api
  local_storage_study_material_api:
    path: packages/crud_packages/local_storage_study_material_api
  cloud_storage_study_material_api:
    path: packages/crud_packages/cloud_storage_study_material_api
  firebase_core: ^2.24.2
  student_api:
    path: packages/crud_packages/student_api
  local_student_api:
    path: packages/crud_packages/local_student_api
  cloud_student_api:
    path: packages/crud_packages/cloud_student_api
  animate_do: ^3.1.2
  hive_flutter: ^1.1.0
  dotted_border: ^2.1.0
  file_picker: ^6.1.1
  share_plus: ^7.2.1
  iconsax: ^0.0.8
  flutter_svg: ^2.0.9
  firebase_storage: ^11.6.0
  intl: ^0.19.0
  cloud_firestore: ^4.14.0
  dio: ^5.4.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.4
  flutter_launcher_icons: ^0.13.1
  banner_carousel: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.0.0  
  mocktail: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  image_path: "assets/images/logo.jpeg"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/lottie/
   - assets/images/
   - assets/icon/
   - assets/images/intro/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
dependency_overrides:
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  flutter_bloc: ^8.1.1
