# Generated by Django 5.1 on 2024-08-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('type', models.CharField(choices=[('NOTE', 'Note'), ('BOOK', 'Book'), ('VIDEO', 'Video')], max_length=50)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='study_materials/')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('fans', models.JSONField(default=list)),
                ('haters', models.JSONField(default=list)),
                ('reports', models.JSONField(default=list)),
            ],
        ),
    ]
