Map<String, Map<String, Map<String, Map<String, List<String>>>>> data = {
  'UNZA': {
    'MEDICINE': {
      'BACHELOR OF MEDICINE AND SURGERY': {},
      'BACHELOR OF HUMAN BIOLOGY': {},
    },
    'ENGINEERING': {
      'AGRICULTURAL ENGINEERING': {},
      'CIVIL AND ENVIRONMENTAL ENGINEERING': {},
      'ELECTRICAL AND ELECTRONIC ENGINEERING': {
        '4': [
          'MAT 4119 - ENGINEERING MATHEMATICS III',
          'ENG 4129 - ENGINEERING MANAGEMENT & ENTREPRENEURSHIP',
          'EEE 4021 - ENGINEERING ELECTROMAGNETICS',
          'EEE 4352 - ELECTRICAL MACHINES',
          'EEE 4362 - ELECTRICAL POWER SYSTEMS I',
          'ENG 4143 - INDUSTRIAL TRAINING I',
          'EEE 4221 - DIGITAL SIGNAL PROCESSING',
          'EEE 4135 - MICROCONTROLLER TECHNOLOGY AND EMBEDDED SYSTEMS',
          'EEE 4242 - ELECTRICAL INSTRUMENTATION',
          'EEE 4571 - ELECTRONIC ENGINEERING II',
        ],
        '3': [
          'MAT 3110 - ENGINEERING MATHEMATICS II',
          'EEE 3132 - COMPUTER ENGINEERING',
          'EEE 3112 - ELECTRICAL ENGINEERING PRACTICE',
          'ENG 3165 - FLUID MECHANICS AND THERMODYNAMICS',
          'EEE 3571 - ELECTRONIC ENGINEERING I',
          'EEE 3131 - DIGITAL ELECTRONICS',
          'EEE 3121 - SIGNALS AND SYSTEMS',
          'EEE 3352 - ELECTRO MECHANICS AND MACHINES',
        ],
        '2': [
          'MAT 2110 - ENGINEERING MATHEMATICS I',
          'MEC 2309 - PROPERTIES OF ENGINEERING MATERIALS I',
          'MEC 2009 - ENGINEERING DRAWING I',
          'EEE 2019 - PRINCIPLES OF ELECTRICAL AND ELECTRONIC ENGINEERING',
          'ENG 2139 - INTRODUCTION TO INFORMATION TECHNOLOGY',
          'ENG 2129 - ENGINEERING AND COMMUNICATION',
          'CEE 2219 - STATICS & INTRODUCTION TO MECHANICS OF MATERIALS',
          'ENG 2159 - MECHANICAL-ELECTRICAL WORKSHOP TECHNOLOGY',
        ],
      },
      'GEOMATIC ENGINEERING': {},
      'MECHANICAL ENGINEERING': {},
    },
    'NATURAL SCIENCES': {
      'COMPUTER SCIENCE': {},
      'COMPUTER SYSTEMS ENGINEERING': {},
      'NETWORKING AND INFORMATION SECURITY': {},
      'SOFTWARE ENGINEERING': {},
      'ACTUARIAL SCIENCE': {},
      'BIOLOGICAL SCIENCES': {},
      'BIOLOGY': {},
      'CHEMICAL & BIOLOGICAL SCIENCES': {},
      'CHEMISTRY': {},
      'MATHEMATICS': {},
      'MICROBIOLOGY': {},
      'MOLECULAR BIOLOGY AND GENETICS': {},
      'NATURAL RESOURCES': {},
      'PARASITOLOGY': {},
      'PHYSICS': {},
      'STATISTICS': {},
    },
  }
};

enum Types { notes, papers, books, links, assignment, lab }
