Map<String, Map<String, Map<String, Map<String, List<String>>>>> data = {
  'UNZA': {
    'MEDICINE': {
      'BACHELOR OF MEDICINE AND SURGERY': {},
      'BACHELOR OF HUMAN BIOLOGY': {},
    },
    'BACHELOR OF ENGINEERING': {
      'AGRICULTURAL ENGINEERING': {
        '2': secondYearBeng,
        '1': firstYearNonMed,
      },
      'CIVIL AND ENVIRONMENTAL ENGINEERING': {
        '3': [
          'MAT 3110 - ENGINEERING MATHEMATICS II',
          'GGY 3051 - ENGINEERING GEOLOGY	',
          'GEE 3522 - LAND LAW AND LAND RESOURCE MANAGEMENT',
          'CEE 3211 - MECHANICS OF MATERIALS',
          'CEE 3222 - THEORY OF STRUCTURES',
          'CEE 3112 - CIVIL ENGINEERING DRAWING',
          'CEE 3111 - CIVIL ENGINEERING MATERIALS & PRACTICES',
          'CEE 3311 - FLUID MECHANICS',
        ],
        '2': secondYearBeng,
        '1': firstYearNonMed
      },
      'ELECTRICAL AND ELECTRONIC ENGINEERING': {
        '5': [
          'ENG 5129 - ENGINEERING MANAGEMENT AND SOCIETY II',
          'EEE 5014 - PROJECT',
          'EEE 5362 - ELECTRICAL POWER SYSTEMS II',
          'EEE 5240 - SYSTEMS AND CONTROL ENGINEERING',
          'EEE 5351 - ELECTRICAL MACHINES II',
          'EEE 5451 - POWER ELECTRONICS',
          'ENG 5143 - INDSTRIAL TRAINING II',
        ],
        '4': [
          'MAT 4119 - ENGINEERING MATHEMATICS III',
          'ENG 4129 - ENGINEERING MANAGEMENT & ENTREPRENEURSHIP',
          'EEE 4021 - ENGINEERING ELECTROMAGNETICS',
          'EEE 4352 - ELECTRICAL MACHINES',
          'EEE 4362 - ELECTRICAL POWER SYSTEMS I',
          'ENG 4143 - INDUSTRIAL TRAINING I',
          'EEE 4221 - DIGITAL SIGNAL PROCESSING',
          'EEE 4135 - MICROCONTROLLER TECHNOLOGY AND EMBEDDED SYSTEMS',
          'EEE 4242 - ELECTRICAL INSTRUMENTATION',
          'EEE 4571 - ELECTRONIC ENGINEERING II',
        ],
        '3': [
          'MAT 3110 - ENGINEERING MATHEMATICS II',
          'EEE 3132 - COMPUTER ENGINEERING',
          'EEE 3112 - ELECTRICAL ENGINEERING PRACTICE',
          'ENG 3165 - FLUID MECHANICS AND THERMODYNAMICS',
          'EEE 3571 - ELECTRONIC ENGINEERING I',
          'EEE 3131 - DIGITAL ELECTRONICS',
          'EEE 3121 - SIGNALS AND SYSTEMS',
          'EEE 3352 - ELECTRO MECHANICS AND MACHINES',
        ],
        '2': secondYearBeng,
        '1': firstYearNonMed,
      },
      'GEOMATIC ENGINEERING': {
        '2': secondYearBeng,
        '1': firstYearNonMed,
      },
      'MECHANICAL ENGINEERING': {
        '2': secondYearBeng,
        '1': firstYearNonMed,
      },
    },
    'BACHELOR OF COMPUTER SCIENCE': {
      'SOFTWARE ENGINEERING': {
        '4': [
          'CSC 4642 - SOFTWARE AND QUALITY ASSURANCE',
          'CSC 4035 - WEB PROGRAMMING AND TECHNOLOGIES',
          'CSC 4631 - SOFTWARE TESTING AND MAINTENANCE',
          'CSC 4630 - ADVANCED SOFTWARE ENGEERING',
          'CSC 4505 - GRAPHICS AND VISUAL COMPUTING',
          'CSC 4004 - PROJECTS',
          'CSC 4792 - DATA MINING AND WAREHOUSING'
        ],
        '3': [
          'CSC 3600 - SOFTWARE ENGINEERING',
          'CSC 3301 - PROGRAMMING LANGUAGES DESIGN & IMPLEMENTAT',
          'CSC 3801 - DATA COMMUNICATION & NETWORKS',
          'CSC 3712 - ADVANCED DATABASES',
          'CSC 3011 - ALGORITHM AND COMPLEXITY',
          'CSC 3612 - IT PROJECT MANAGEMENT',
          'CSC 3402 - FUNDAMENTALS OF ARTIFICIAL INTELLIGENCE',
          'CSC 3009 - INDUSTRIAL TRAINING COURSE',
        ],
        '2': [
          'CSC 2901 - DISCRETE STRUCTURES',
          'CSC 2101 - COMPUTER SYSTEMS',
          'CSC 2702 - DATABASE & INFORMATION MANAGEMENT SYSTEM',
          'CSC 2202 - OPERATING SYSTEMS',
          'CSC 2000 - COMPUTER PROGRAMMING',
          'CSC 2912 - NUMERICAL ANALYSIS',
        ],
        '1': firstYearNonMed,
      },
      'COMPUTER SYSTEMS ENGINEERING': {
        '4': [
          'CSC 4812 - CLOUD AND HIGH-PERFORMANCE COMPUTING',
          'CSC 4835 - WIRELESS AND MOBILE COMPUTING',
          'CSC 4745 - MULTIMEDIA AND HUMAN-COMPUTER INTERACTIONS',
          'CSC 4004 - PROJECTS',
          'CSC 4130 - HARDWARE DESIGN AND IMPLEMENTATION',
          'CSC 4722 - DISTRIBUTED SYSTEMS',
          'CSC 3099 - INDUSTRIAL TRAINING COURSE',
          'CSC 4792 - DATA MINING AND WAREHOUSING',
        ],
        '3': [
          'CSC 3120 - DIGITAL ELECTRONICS',
          'CSC 3301 - PROGRAMMING LANGUAGES DESIGN & IMPLEMENTAT',
          'CSC 3801 - DATA COMMUNICATION & NETWORKS',
          'CSC 3612 - IT PROJECT MANAGEMENT',
          'CSC 3712 - ADVANCED DATABASES',
          'CSC 3011 - ALGORITHM AND COMPLEXITY',
          'CSC 3402 - FUNDAMENTALS OF ARTIFICIAL INTELLIGENCE',
          'CSC 3009 - INDUSTRIAL TRAINING COURSE',
        ],
        '2': [
          'CSC 2901 - DISCRETE STRUCTURES',
          'CSC 2101 - COMPUTER SYSTEMS',
          'CSC 2702 - DATABASE & INFORMATION MANAGEMENT SYSTEM',
          'CSC 2202 - OPERATING SYSTEMS',
          'CSC 2000 - COMPUTER PROGRAMMING',
          'CSC 2912 - NUMERICAL ANALYSIS',
        ],
        '1': firstYearNonMed,
      }
    },
    'NATURAL SCIENCES': {
      'ACTUARIAL SCIENCE': {},
      'BIOLOGICAL SCIENCES': {},
      'BIOLOGY': {},
      'CHEMICAL & BIOLOGICAL SCIENCES': {},
      'CHEMISTRY': {},
      'MATHEMATICS': {},
      'MICROBIOLOGY': {},
      'MOLECULAR BIOLOGY AND GENETICS': {},
      'NATURAL RESOURCES': {},
      'PARASITOLOGY': {},
      'PHYSICS': {},
      'STATISTICS': {},
    },
  }
};

enum Types { notes, papers, books, links, assignment, lab }

const List<String> firstYearNonMed = [
  'PHY 1010 - INTRODUCTORY PHYSICS',
  'CHE 1000 - INTRODUCTORY CHEMISTRY',
  'MAT 1100 - FOUNDATION MATHEMATICS',
  'BIO 1400 - CELLULAR, MOLECULAR BIOLOGY AND GENETICS'
];

const List<String> secondYearBeng = [
  'MAT 2110 - ENGINEERING MATHEMATICS I',
  'MEC 2309 - PROPERTIES OF ENGINEERING MATERIALS I',
  'MEC 2009 - ENGINEERING DRAWING I',
  'EEE 2019 - PRINCIPLES OF ELECTRICAL AND ELECTRONIC ENGINEERING',
  'ENG 2139 - INTRODUCTION TO INFORMATION TECHNOLOGY',
  'ENG 2129 - ENGINEERING AND COMMUNICATION',
  'CEE 2219 - STATICS & INTRODUCTION TO MECHANICS OF MATERIALS',
  'ENG 2159 - MECHANICAL-ELECTRICAL WORKSHOP TECHNOLOGY',
];
