// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIA16qfcFzdvMe8_i_poKNIfW516lhoIw',
    appId: '1:585015455552:web:a06e59e98a797777f2d4a5',
    messagingSenderId: '585015455552',
    projectId: 'reviza-31466',
    authDomain: 'reviza-31466.firebaseapp.com',
    storageBucket: 'reviza-31466.appspot.com',
    measurementId: 'G-7424QCL9BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpyyXFbDWUQmj_6kO5Nc0NZ3ZwJePVNoE',
    appId: '1:585015455552:android:80ad8211e2ed7f24f2d4a5',
    messagingSenderId: '585015455552',
    projectId: 'reviza-31466',
    storageBucket: 'reviza-31466.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKeGraITk7HJEVXyMWqJfc96GMAw-3fZA',
    appId: '1:585015455552:ios:5b44f71d6e13f751f2d4a5',
    messagingSenderId: '585015455552',
    projectId: 'reviza-31466',
    storageBucket: 'reviza-31466.appspot.com',
    iosClientId: '585015455552-smt38qt7qu7q2rccmo7170apo8at3qgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.reviza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKeGraITk7HJEVXyMWqJfc96GMAw-3fZA',
    appId: '1:585015455552:ios:2e6fe7575d5c2240f2d4a5',
    messagingSenderId: '585015455552',
    projectId: 'reviza-31466',
    storageBucket: 'reviza-31466.appspot.com',
    iosClientId: '585015455552-r1l4qbc1mlmd0vfijg2jhuiigveb69n5.apps.googleusercontent.com',
    iosBundleId: 'com.example.reviza.RunnerTests',
  );
}
