name: Test Flutter Application

on:
  push:
    paths:
      - "flutter_app/**"
  pull_request:
    paths:
      - "flutter_app/**"

jobs:
  test_flutter_app:
    name: Validate Flutter App
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: flutter_app

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: stable
          cache: true

      # Step 3: Verify Flutter installation and environment
      - name: Verify Flutter Installation
        run: |
          flutter --version
          flutter doctor

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 5: Verify Build
      - name: Verify Build
        run: flutter build apk --debug

      # Step 6: Run Tests
      - name: Run Tests
        run: flutter test

      # Step 7: Cache results (optional)
      - name: Cache Pub Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-
